# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 'Today I Learned'
email: 'hello@ramottamado.dev'
author: 'Tamado Ramot Sitohang'
description: > # this means to ignore newlines until "url:"
  Today I learned.<br />
  Made with ❤️.
logo: 'favicon.svg'
icon: 'favicon.ico'
fb_app_id: 2815620495116640
fb_pages: 103250301049786
fb_author: 100000091609630
gravatar_author: "https://www.gravatar.com/avatar/90b290098c6a408c075ab0fd3b1f5783?s=300"
linkedin_username: ramottamado
github_username: ramottamado
twitter_username: theramottamado
ig_username: theramottamado
fb_username: theramottamado
google_site_verification: 'zaJj36ddah20RkBG1RrQqWm-IlXepNuw8ch6SYXeBPQ'
permalink: /:title/
excerpt_separator: <!--more-->
sitemap:
  changefreq: monthly

nav_pages:
  - about.md

fb_article: true
disable_social: true

remote_theme: ramottamado/nadya

# Build settings
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    default_lang: html
